name: Antora Test Site 

on:
  push:
    branches: 
      - master

jobs:
  build_site:
    name: "Build site with Antora"
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Generate site using antora site action"
        uses: kameshsampath/antora-site-action@master
        with:
         antora_playbook: antora-playbook.yml
      - name: "List folder"
        run: |
           ls -ltr $GITHUB_WORKSPACE/build
      - name: "Upload generated site"
        uses: actions/upload-artifact@v1.0.0
        with:
          name: site
          path: $GITHUB_WORKSPACE/docs
  deploy_site:
    runs-on: [ubuntu-latest]
    needs: [build_site]
    name: "Deploy GitHub Pages"
    steps:
     - name: Setup Node.js for use with actions
       uses: actions/setup-node@v1.1.0
       with:
         version: 12.x
     - name: Checkout
       uses: actions/checkout@v2
     - name: Download generated site
       uses: actions/download-artifact@v1
       with:
         name: site
     - name: Install gh-pages 
       id: install-gh-pages
       run: |
         npm -g install gh-pages@2.2.0
         git config user.email "kamesh.sampath@hotmail.com"
         git config user.name "kameshsampath"
     - name: Deploy site
       run: |
         gh-pages --dotfiles --message "[skip ci] Publishing new documentation" --dist gh-pages
       
      
        
